import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Gnb from '@/components/common/Gnb';
import Footer from '@/components/common/Footer';
import dynamic from 'next/dynamic';

const ModalProvider = dynamic(() => import('@/providers/ModalProvider'), { ssr: false });

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <Gnb />
        {children}
        <Footer />
        <ModalProvider />
        <div id="root-portal"></div>
      </body>
    </html>
  );
}
