import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import QueryProvider from '@/providers/QueryProvider';
import ModalProvider from '@/providers/ModalProvider';
import Gnb from '@/components/common/Gnb';

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <QueryProvider>
          <Gnb />
          {children}
          <ModalProvider />
          <div id="root-portal"></div>
        </QueryProvider>
      </body>
    </html>
  );
}
